use_frameworks!

platform :ios, '10.0'

target 'TAAuthenticationUI_Example' do
  pod 'TAAuthenticationUI', :path => '../'

  target 'TAAuthenticationUI_Tests' do
    inherit! :search_paths

    
  end
end
