#platform :ios, '12.0'
use_frameworks!

target 'TAAuthenticationUI_Example' do
  pod 'TAAuthenticationUI', :path => '../'
  pod 'Alamofire', '~> 5.4'
  pod 'ObjectMapper', '~> 4.2'
  
  target 'TAAuthenticationUI_Tests' do
    inherit! :search_paths

    
  end
end
